version: '3'
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/repository:/tmp/repository
    environment:
      USER: user
      REPO: repo
      TOKEN: token
      WORKDIR: /tmp/repository
    