version: '3'
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      REPOSITORY: $$$
      TOKEN: $$$
    